import createClient from 'openapi-fetch';
import type { paths } from './contract'; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: 'http://localhost:8080' });

const { data, error } = await client.GET('/api/hello', {
	params: {
		query: {
			name: 'Elias',
		},
	},
});

client.POST('/api/file', {
	body: {
		file: '{ sarasa: 1}',
	},
});

console.log(await client.GET('/api/hello/{name}', { params: { path: { name: 'Elias' } } }));

console.log(data);
console.log(error);
