/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/file': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations['postApiFile'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/hello/{name}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['getApiHelloByName'];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/api/hello': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations['getApiHello'];
		put?: never;
		post: operations['postApiHello'];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: never;
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	postApiFile: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: {
			content: {
				'multipart/form-data': {
					/** Format: binary */
					file: string;
				};
			};
		};
		responses: never;
	};
	getApiHelloByName: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: never;
	};
	getApiHello: {
		parameters: {
			query: {
				name: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						first: number;
					};
				};
			};
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						message: string;
						/** @enum {number} */
						status: 400;
					};
				};
			};
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					'application/json': {
						message: string;
						/** @enum {number} */
						status: 500;
					};
				};
			};
		};
	};
	postApiHello: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: {
			content: {
				'multipart/form-data': {
					name: string;
					/** Format: binary */
					file: string;
				};
			};
		};
		responses: never;
	};
}
