/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/employee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEmployee"];
        put?: never;
        post: operations["postEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employee/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEmployeeById"];
        put: operations["putEmployeeById"];
        post?: never;
        delete: operations["deleteEmployeeById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getEmployee: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                trash?: boolean | unknown | unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total: number;
                        pageSize: number;
                        pages: number;
                        currentPage: number;
                        prevPage: number | null;
                        nextPage: number | null;
                        data: {
                            _id: unknown;
                            /** @default null */
                            deletedAt: unknown | null;
                            /** @default 2025-08-20T22:36:10.933Z */
                            createdAt: unknown;
                            /** @default null */
                            updatedAt: unknown | null;
                            /** @default 9a44789e-12d3-415f-9ca8-7cb1dfa73e89 */
                            uuid: string;
                            name: string;
                            lastName: string;
                            /** @default null */
                            birthDate: unknown | null;
                            /** @default true */
                            active: boolean;
                            /** @default null */
                            salary: number | null;
                            /** @enum {string} */
                            gender: "male" | "female" | "none";
                            sub: {
                                a: string;
                                b: string;
                            };
                        }[];
                    };
                };
            };
            /** @description 400 Response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: number;
                    };
                };
            };
        };
    };
    postEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description POST /employee Body */
        requestBody: {
            content: {
                /** @example {
                 *       "uuid": "6d010d99-a163-42b4-8da5-bfaa8749478c",
                 *       "name": "<string format>",
                 *       "lastName": "<string format>",
                 *       "birthDate": "2025-08-20 19:36:10",
                 *       "salary": 10.5,
                 *       "gender": "male",
                 *       "sub": {
                 *         "a": "<string format>",
                 *         "b": "<string format>"
                 *       }
                 *     } */
                "application/json": {
                    /** @default 320bf4f3-5510-470d-817a-a3e3ea4eb398 */
                    uuid: string;
                    name: string;
                    lastName: string;
                    /** @default null */
                    birthDate: unknown | null;
                    /** @default true */
                    active: boolean;
                    /** @default null */
                    salary: number | null;
                    /** @enum {string} */
                    gender: "male" | "female" | "none";
                    sub: {
                        a: string;
                        b: string;
                    };
                };
            };
        };
        responses: {
            /** @description Unknown */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getEmployeeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example id-example */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "uuid": "6d010d99-a163-42b4-8da5-bfaa8749478c",
                     *       "name": "<string format>",
                     *       "lastName": "<string format>",
                     *       "birthDate": "2025-08-20 19:36:10",
                     *       "salary": 10.5,
                     *       "gender": "male",
                     *       "sub": {
                     *         "a": "<string format>",
                     *         "b": "<string format>"
                     *       }
                     *     } */
                    "application/json": {
                        _id: unknown;
                        /** @default null */
                        deletedAt: unknown | null;
                        /** @default 2025-08-20T22:36:10.935Z */
                        createdAt: unknown;
                        /** @default null */
                        updatedAt: unknown | null;
                        /** @default 98b69177-8fba-4d9d-ab37-51089c54f059 */
                        uuid: string;
                        name: string;
                        lastName: string;
                        /** @default null */
                        birthDate: unknown | null;
                        /** @default true */
                        active: boolean;
                        /** @default null */
                        salary: number | null;
                        /** @enum {string} */
                        gender: "male" | "female" | "none";
                        sub: {
                            a: string;
                            b: string;
                        };
                    };
                };
            };
            /** @description 404 Response */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status: number;
                    };
                };
            };
        };
    };
    putEmployeeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example id-example */
                id: string;
            };
            cookie?: never;
        };
        /** @description PUT /employee/:id Body */
        requestBody: {
            content: {
                "application/json": {
                    /** @default null */
                    deletedAt?: unknown | null;
                    /** @default 2025-08-20T22:36:10.936Z */
                    createdAt?: unknown;
                    /** @default null */
                    updatedAt?: unknown | null;
                    /** @default c5928ca3-1715-47d9-b639-7aaeb1175f80 */
                    uuid?: string;
                    name?: string;
                    lastName?: string;
                    /** @default null */
                    birthDate?: unknown | null;
                    /** @default true */
                    active?: boolean;
                    /** @default null */
                    salary?: number | null;
                    /** @enum {string} */
                    gender?: "male" | "female" | "none";
                    sub?: {
                        a: string;
                        b: string;
                    };
                };
            };
        };
        responses: {
            /** @description Unknown */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteEmployeeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example id-example */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success: boolean;
                    };
                };
            };
        };
    };
    post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description POST / Body */
        requestBody: {
            content: {
                /** @example {
                 *       "ex": "my example string"
                 *     } */
                "application/json": {
                    ex: string;
                };
            };
        };
        responses: {
            /** @description Unknown */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
