import createClient from 'openapi-fetch';
import type { paths } from './example-schema'; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: 'http://localhost:8080' });

const { data, error } = await client.GET('/employee/{id}', {
	params: {
		path: {
			id: '68a607d7296642f997fe2e',
		},
	},
});

const { data: data2, error: error2 } = await client.GET('/employee', {
	params: {
		query: {
			page: 1,
			pageSize: 50,
		},
	},
});

const { data: data3, error: error3 } = await client.POST('/employee', {
	body: {
		salary: 150,
		birthDate: '2025-01-01',
	},
});

console.log({
	data,
	error,
});

console.log({
	data2,
	error2,
});
